/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as UserRouteImport } from './routes/_user';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as UserCardsRouteImport } from './routes/_user/cards';
import { Route as AdminIndexRouteImport } from './routes/admin/index';
import { Route as AdminProductsRouteImport } from './routes/admin/products';
import { Route as UserSettingsCommonExcludeKeywordsRouteImport } from './routes/_user/settings/common-exclude-keywords';
import { Route as UserWatchesIndexRouteImport } from './routes/_user/watches/index';
import { Route as UserWatchesCardIdRouteImport } from './routes/_user/watches/$cardId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const UserCardsRoute = UserCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => UserRoute,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any);
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any);
const UserSettingsCommonExcludeKeywordsRoute =
  UserSettingsCommonExcludeKeywordsRouteImport.update({
    id: '/settings/common-exclude-keywords',
    path: '/settings/common-exclude-keywords',
    getParentRoute: () => UserRoute,
  } as any);
const UserWatchesIndexRoute = UserWatchesIndexRouteImport.update({
  id: '/watches/',
  path: '/watches/',
  getParentRoute: () => UserRoute,
} as any);
const UserWatchesCardIdRoute = UserWatchesCardIdRouteImport.update({
  id: '/watches/$cardId',
  path: '/watches/$cardId',
  getParentRoute: () => UserRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin': typeof AdminRouteWithChildren;
  '/cards': typeof UserCardsRoute;
  '/admin/products': typeof AdminProductsRoute;
  '/admin/': typeof AdminIndexRoute;
  '/settings/common-exclude-keywords': typeof UserSettingsCommonExcludeKeywordsRoute;
  '/watches/$cardId': typeof UserWatchesCardIdRoute;
  '/watches/': typeof UserWatchesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/cards': typeof UserCardsRoute;
  '/admin/products': typeof AdminProductsRoute;
  '/admin': typeof AdminIndexRoute;
  '/settings/common-exclude-keywords': typeof UserSettingsCommonExcludeKeywordsRoute;
  '/watches/$cardId': typeof UserWatchesCardIdRoute;
  '/watches': typeof UserWatchesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_user': typeof UserRouteWithChildren;
  '/admin': typeof AdminRouteWithChildren;
  '/_user/cards': typeof UserCardsRoute;
  '/admin/products': typeof AdminProductsRoute;
  '/admin/': typeof AdminIndexRoute;
  '/_user/settings/common-exclude-keywords': typeof UserSettingsCommonExcludeKeywordsRoute;
  '/_user/watches/$cardId': typeof UserWatchesCardIdRoute;
  '/_user/watches/': typeof UserWatchesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/cards'
    | '/admin/products'
    | '/admin/'
    | '/settings/common-exclude-keywords'
    | '/watches/$cardId'
    | '/watches/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/cards'
    | '/admin/products'
    | '/admin'
    | '/settings/common-exclude-keywords'
    | '/watches/$cardId'
    | '/watches';
  id:
    | '__root__'
    | '/'
    | '/_user'
    | '/admin'
    | '/_user/cards'
    | '/admin/products'
    | '/admin/'
    | '/_user/settings/common-exclude-keywords'
    | '/_user/watches/$cardId'
    | '/_user/watches/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  UserRoute: typeof UserRouteWithChildren;
  AdminRoute: typeof AdminRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_user': {
      id: '/_user';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof UserRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_user/cards': {
      id: '/_user/cards';
      path: '/cards';
      fullPath: '/cards';
      preLoaderRoute: typeof UserCardsRouteImport;
      parentRoute: typeof UserRoute;
    };
    '/admin/': {
      id: '/admin/';
      path: '/';
      fullPath: '/admin/';
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/admin/products': {
      id: '/admin/products';
      path: '/products';
      fullPath: '/admin/products';
      preLoaderRoute: typeof AdminProductsRouteImport;
      parentRoute: typeof AdminRoute;
    };
    '/_user/settings/common-exclude-keywords': {
      id: '/_user/settings/common-exclude-keywords';
      path: '/settings/common-exclude-keywords';
      fullPath: '/settings/common-exclude-keywords';
      preLoaderRoute: typeof UserSettingsCommonExcludeKeywordsRouteImport;
      parentRoute: typeof UserRoute;
    };
    '/_user/watches/': {
      id: '/_user/watches/';
      path: '/watches';
      fullPath: '/watches/';
      preLoaderRoute: typeof UserWatchesIndexRouteImport;
      parentRoute: typeof UserRoute;
    };
    '/_user/watches/$cardId': {
      id: '/_user/watches/$cardId';
      path: '/watches/$cardId';
      fullPath: '/watches/$cardId';
      preLoaderRoute: typeof UserWatchesCardIdRouteImport;
      parentRoute: typeof UserRoute;
    };
  }
}

interface UserRouteChildren {
  UserCardsRoute: typeof UserCardsRoute;
  UserSettingsCommonExcludeKeywordsRoute: typeof UserSettingsCommonExcludeKeywordsRoute;
  UserWatchesCardIdRoute: typeof UserWatchesCardIdRoute;
  UserWatchesIndexRoute: typeof UserWatchesIndexRoute;
}

const UserRouteChildren: UserRouteChildren = {
  UserCardsRoute: UserCardsRoute,
  UserSettingsCommonExcludeKeywordsRoute:
    UserSettingsCommonExcludeKeywordsRoute,
  UserWatchesCardIdRoute: UserWatchesCardIdRoute,
  UserWatchesIndexRoute: UserWatchesIndexRoute,
};

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren);

interface AdminRouteChildren {
  AdminProductsRoute: typeof AdminProductsRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UserRoute: UserRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
